name: PHPUnit (focused)

on:
  workflow_dispatch:
  push:
    paths:
      - 'tests/**'
      - 'includes/**'
      - 'run-tests.sh'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, curl, zip

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git unzip default-mysql-client

      - name: Get Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Prepare WordPress tests directory
        env:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
        run: |
          if [ ! -d "$WP_TESTS_DIR" ]; then
            git clone https://github.com/WordPress/wordpress-develop.git "$WP_TESTS_DIR"
          fi

      - name: Ensure test DB exists
        env:
          DB_NAME: puntwork_test
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do mysqladmin ping -h127.0.0.1 >/dev/null 2>&1 && break || sleep 1; done
          mysql -h127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"

      - name: Run focused PHPUnit test
        env:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
        run: |
          chmod +x ./run-tests.sh
          ./run-tests.sh tests/TestDownloadFeed.php
